Add Cloud Prometheus and Loki

diff --git a/.github/workflows/mlops_workflow.yml b/.github/workflows/mlops_workflow.yml
--- a/.github/workflows/mlops_workflow.yml
+++ b/.github/workflows/mlops_workflow.yml
@@ -9,6 +9,42 @@ on:
             - main
 
 jobs:
+    monitoring_setup:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v2
+
+            - name: Install ngrok
+              run: |
+                  curl -Lo ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
+                  unzip ngrok.zip
+                  chmod +x ngrok
+                  sudo mv ngrok /usr/local/bin
+
+            - name: Start monitoring stack
+              run: |
+                  docker-compose -f docker-compose.monitoring.yml up -d
+
+            - name: Start ngrok tunnels
+              env:
+                  NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
+              run: |
+                  ngrok authtoken $NGROK_AUTHTOKEN
+                  ngrok start --all --config ngrok.yml &
+                  sleep 10
+                  curl http://localhost:4040/api/tunnels > tunnels.json
+
+                  # Extract URLs
+                  GRAFANA_URL=$(jq -r '.tunnels[] | select(.name=="grafana") | .public_url' tunnels.json)
+                  PROMETHEUS_URL=$(jq -r '.tunnels[] | select(.name=="prometheus") | .public_url' tunnels.json)
+                  LOKI_URL=$(jq -r '.tunnels[] | select(.name=="loki") | .public_url' tunnels.json)
+
+                  # Save URLs as artifacts
+                  echo "GRAFANA_URL=$GRAFANA_URL" >> $GITHUB_ENV
+                  echo "PROMETHEUS_URL=$PROMETHEUS_URL" >> $GITHUB_ENV
+                  echo "LOKI_URL=$LOKI_URL" >> $GITHUB_ENV
+
     # Step 1: Build Base Image with Dependencies
     build_and_cache_dependencies:
         runs-on: ubuntu-latest
@@ -39,7 +75,7 @@ jobs:
             mlflow:
                 image: ghcr.io/mlflow/mlflow:v2.18.0rc0
                 ports:
-                  - 5000:5000
+                    - 5000:5000
 
         steps:
             - name: Checkout repository
@@ -48,11 +84,10 @@ jobs:
             # Set up Prometheus configuration directory and remove existing Prometheus container if exists
             - name: Set up Prometheus configuration and start Prometheus
               run: |
-                  # Set up Prometheus configuration
                   mkdir -p ./prometheus_config
                   cp prometheus.yml ./prometheus_config/prometheus.yml
 
-                  # Stop and remove existing Prometheus container, if any
+                  # Stop and remove existing Prometheus container
                   docker stop prometheus || true
                   docker rm prometheus || true
 
@@ -60,15 +95,26 @@ jobs:
                   docker run -d --name prometheus -p 9090:9090 \
                     -v $(pwd)/prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus:latest
 
+            # Debugging: Log environment variables to ensure they are set correctly
+            - name: Debugging - Log environment variables
+              run: |
+                  echo "DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}"
+                  echo "DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}"
+                  echo "SUPABASE_S3_ENDPOINT: ${{ secrets.SUPABASE_S3_ENDPOINT }}"
+                  echo "SUPABASE_S3_REGION: ${{ secrets.SUPABASE_S3_REGION }}"
+                  echo "SUPABASE_S3_ACCESS_KEY_ID: ${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}"
+                  echo "SUPABASE_S3_SECRET_ACCESS_KEY: ${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}"
+
             - name: Pull and Run Dependency Image
               env:
                   SUPABASE_S3_ENDPOINT: ${{ secrets.SUPABASE_S3_ENDPOINT }}
                   SUPABASE_S3_REGION: ${{ secrets.SUPABASE_S3_REGION }}
                   SUPABASE_S3_ACCESS_KEY_ID: ${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}
                   SUPABASE_S3_SECRET_ACCESS_KEY: ${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}
-                  MLFLOW_TRACKING_URI: http://localhost:5000
+                  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
+                  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
               run: |
-                  # Pull the Docker dependency image with retry mechanism to avoid temporary network issues
+                  # Pull the Docker dependency image with retry mechanism
                   n=0
                   until [ "$n" -ge 5 ]
                   do
@@ -79,39 +125,56 @@ jobs:
                   done
 
                   # Run the Docker container with dependencies
-                  docker run --rm -v ${{ github.workspace }}:/app -w /app ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest bash -c "
-                    # Git configuration
-                    git config --global user.email 'actions@github.com' &&
-                    git config --global user.name 'GitHub Actions' &&
-                    
-                    # Stop tracking dataset and model folders with Git
-                    git rm -r --cached dataset || true &&
-                    git rm -r --cached model || true &&
-                    git commit -m 'Stop tracking dataset and model' --allow-empty &&
-                    
-                    # DVC setup and configuration
-                    dvc remote add -d supabase-s3 s3://MLOps --force &&
-                    dvc remote modify supabase-s3 endpointurl '$SUPABASE_S3_ENDPOINT' &&
-                    dvc remote modify supabase-s3 region '$SUPABASE_S3_REGION' &&
-                    dvc remote modify supabase-s3 access_key_id '$SUPABASE_S3_ACCESS_KEY_ID' &&
-                    dvc remote modify supabase-s3 secret_access_key '$SUPABASE_S3_SECRET_ACCESS_KEY' &&
-                    
-                    # Pull the dataset from the DVC remote
-                    dvc pull &&
-                    
-                    # Check dataset directory for debugging
-                    echo 'Contents of dataset/train directory:' &&
-                    ls /app/dataset/train &&
-                    
-                    # Run the training script
-                    python script/train.py &&
-                    
-                    # Push updated model and dataset changes back to DVC remote
-                    dvc push &&
+                  docker run --rm \
+                      -e SUPABASE_S3_ENDPOINT="$SUPABASE_S3_ENDPOINT" \
+                      -e SUPABASE_S3_REGION="$SUPABASE_S3_REGION" \
+                      -e SUPABASE_S3_ACCESS_KEY_ID="$SUPABASE_S3_ACCESS_KEY_ID" \
+                      -e SUPABASE_S3_SECRET_ACCESS_KEY="$SUPABASE_S3_SECRET_ACCESS_KEY" \
+                      -e DAGSHUB_USERNAME="$DAGSHUB_USERNAME" \
+                      -e DAGSHUB_TOKEN="$DAGSHUB_TOKEN" \
+                      -e MLFLOW_TRACKING_URI="http://localhost:5000" \
+                      -v ${{ github.workspace }}:/app -w /app ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest bash -c "
+                        echo 'Starting training...' &&
+                        echo 'Environment Variables in Container:' &&
+                        echo 'DAGSHUB_USERNAME: $DAGSHUB_USERNAME' &&
+                        echo 'DAGSHUB_TOKEN: $DAGSHUB_TOKEN' &&
+                        echo 'SUPABASE_S3_ENDPOINT: $SUPABASE_S3_ENDPOINT' &&
+                        echo 'SUPABASE_S3_REGION: $SUPABASE_S3_REGION' &&
+                        echo 'SUPABASE_S3_ACCESS_KEY_ID: $SUPABASE_S3_ACCESS_KEY_ID' &&
+                        echo 'SUPABASE_S3_SECRET_ACCESS_KEY: $SUPABASE_S3_SECRET_ACCESS_KEY' &&
 
-                    # Run the test script
-                    python script/test.py
-                  "
+                        # Git configuration
+                        git config --global user.email 'actions@github.com' &&
+                        git config --global user.name 'GitHub Actions' &&
+                        
+                        # Stop tracking dataset and model folders with Git
+                        git rm -r --cached dataset || true &&
+                        git rm -r --cached model || true &&
+                        git commit -m 'Stop tracking dataset and model' --allow-empty &&
+                        
+                        # DVC setup and configuration
+                        dvc remote add -d supabase-s3 s3://MLOps --force &&
+                        dvc remote modify supabase-s3 endpointurl '$SUPABASE_S3_ENDPOINT' &&
+                        dvc remote modify supabase-s3 region '$SUPABASE_S3_REGION' &&
+                        dvc remote modify supabase-s3 access_key_id '$SUPABASE_S3_ACCESS_KEY_ID' &&
+                        dvc remote modify supabase-s3 secret_access_key '$SUPABASE_S3_SECRET_ACCESS_KEY' &&
+                        
+                        # Pull the dataset from the DVC remote
+                        dvc pull &&
+                        
+                        # Check dataset directory for debugging
+                        echo 'Contents of dataset/train directory:' &&
+                        ls /app/dataset/train &&
+                        
+                        # Run the training script
+                        python script/train.py &&
+                        
+                        # Push updated model and dataset changes back to DVC remote
+                        dvc push &&
+
+                        # Run the test script
+                        python script/test.py
+                      "
 
     # Step 3: Build and Push Final Docker Image with Model
     build_and_push_docker:
